version: "3"

services:
  minecraft-server:
    build:
      context: .
      args:
        - RAM_AMOUNT = ${RAM_AMOUNT}
    ports:
      - 25565:25565
      - 25575:25575
    container_name: ${CONTAINER_NAME}
    volumes:
      - .server-data:/server

volumes:
  server-data: